// Copyright (c) 2026, Dutch Digitech and contributors
// For license information, please see license.txt

// Variation build 2: the editable surface is `bill_entries` (one row per
// item, with cumulative_qty). The `items` table is GENERATED by the
// server allocator (validate() splits bill_entries left-to-right across
// scopes) and is read-only to the user.
//
// No live recompute handlers here — the allocation is server-side and
// depends on prior submitted bills (database state) which the client
// can't replicate cheaply. Server validate() is the source of truth;
// the user sees the per-scope items table after save.
//
// Per CLAUDE.md 1.5c.6: NO refresh() handler that mutates child tables.

frappe.ui.form.on("Work Order RA Bill", {
	setup(frm) {
		// Filter summary_head pickers (defensive — both tables are
		// read-only, but preserves the filter if a future change re-opens
		// editability).
		frm.set_query("summary_head", "items", () => ({
			filters: { item_group: "Work Order Items", disabled: 0 },
		}));
		frm.set_query("summary_head", "bill_entries", () => ({
			filters: { item_group: "Work Order Items", disabled: 0 },
		}));
	},
});
