// Copyright (c) 2026, Dutch Digitech and contributors
// For license information, please see license.txt

// Variation build 2: the editable surface is `bill_entries` (one row per
// item, with cumulative_qty). The `items` table is GENERATED by the
// server allocator (validate() splits bill_entries left-to-right across
// scopes) and is read-only to the user.
//
// No live recompute handlers here — the allocation is server-side and
// depends on prior submitted bills (database state) which the client
// can't replicate cheaply. Server validate() is the source of truth;
// the user sees the per-scope items table after save.
//
// Per CLAUDE.md 1.5c.6: NO refresh() handler that mutates child tables.
// The civil_work_order handler below DOES mutate bill_entries — that's
// safe because it fires on a USER FIELD EDIT (not on refresh), so the
// resulting dirty state corresponds to a real user change.

frappe.ui.form.on("Work Order RA Bill", {
	setup(frm) {
		// Filter summary_head pickers (defensive — both tables are
		// read-only, but preserves the filter if a future change re-opens
		// editability).
		frm.set_query("summary_head", "items", () => ({
			filters: { item_group: "Work Order Items", disabled: 0 },
		}));
		frm.set_query("summary_head", "bill_entries", () => ({
			filters: { item_group: "Work Order Items", disabled: 0 },
		}));

		// Lock down bill_entries grid: rows are populated by the server
		// from the WO's scope map (one per item, with the right item_key).
		// A hand-added row would lack item_key and break per-scope
		// allocation. Disable Add and Delete on the grid so the only way
		// to change which items are present is to change the Work Order.
		// (Cumulative qty per row stays editable — that's the engineer's
		// surface.) Mirror discipline on items, which is already read-only
		// at the doctype level — this just makes the grid affordances match.
		frm.set_df_property("bill_entries", "cannot_add_rows", true);
		frm.set_df_property("bill_entries", "cannot_delete_rows", true);
		frm.set_df_property("items", "cannot_add_rows", true);
		frm.set_df_property("items", "cannot_delete_rows", true);
	},

	civil_work_order(frm) {
		// Auto-populate bill_entries when the engineer picks the Work
		// Order, so the table doesn't sit empty inviting manual rows
		// (manual rows would lack the item_key the allocator needs).
		//
		// Reuses the server's populate_bill_entries_from_scope_map via a
		// whitelisted module-level wrapper — same code that runs at save
		// time, so the on-select path and the on-save path always produce
		// identical entries.
		const wo = frm.doc.civil_work_order;
		if (!wo) return;
		// Skip while the form is mid-load (Frappe sets the field during
		// document load and fires this handler; we don't want to clobber
		// the persisted bill_entries on an existing doc).
		if (frm.doc.__islocal !== 1) return;

		const existing = (frm.doc.bill_entries || []).filter(
			(r) => r.item_key
		);
		const has_typed_data = existing.some(
			(r) => (parseFloat(r.cumulative_qty) || 0) > 0
		);

		const doPopulate = () => populate_entries(frm, wo, existing);

		if (has_typed_data) {
			// Changing to a different WO will discard the typed qtys for
			// the old WO. Confirm before destroying user data.
			frappe.confirm(
				__(
					"Changing the Work Order will reset the Bill Entries. " +
						"Cumulative quantities you have already typed for the " +
						"previous Work Order will be lost. Continue?"
				),
				doPopulate,
				() => {
					// User cancelled — nothing to do; their typed data
					// remains and the new WO link sits without populating.
					// (We don't try to revert the link because the prior
					// value isn't reliably available here; the user can
					// re-pick if needed.)
				}
			);
		} else {
			doPopulate();
		}
	},
});

function populate_entries(frm, wo, existing) {
	frappe.call({
		method: "dux_civil_works.dux_work_orders.doctype.work_order_ra_bill.work_order_ra_bill.get_initial_bill_entries",
		args: {
			work_order_contract: wo,
			existing_entries: JSON.stringify(
				(existing || []).map((r) => ({
					item_key: r.item_key,
					cumulative_qty: r.cumulative_qty,
					remarks: r.remarks,
				}))
			),
		},
		freeze: true,
		freeze_message: __("Loading items from Work Order..."),
		callback: (r) => {
			if (!r || !r.message) return;
			frm.clear_table("bill_entries");
			(r.message || []).forEach((row) => {
				const child = frm.add_child("bill_entries");
				Object.assign(child, row);
			});
			frm.refresh_field("bill_entries");
		},
	});
}
